Repository Kumar77758/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#1 Quote Added
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest

#2 Added Coding Quote
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest

#3 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest

#5 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#9 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#7 added my fav quote
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#8 himanshu added quote
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest

#10 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#11 Updated Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#12 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#13 Update Quote.md
  Quote.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2022
